var name = "Prachi";
var school = "Masai School";
var grade = "A";
var section = "B";
var rollno = 89;
var maths = 90;
var english = 95;
var science = 92;
console.log("★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★");
console.log("             STUDENT REPORT CARD                    ");
console.log("★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★=★\n");
console.log("-----------------------------------------------------\n");
console.log("              Personal Information                 \n");
console.log("-----------------------------------------------------");
console.log("Name: " + name);
console.log("School: " + school);
console.log("Grade: " + grade);
console.log("Section: " + section);
console.log("Roll No: " + rollno);
console.log("Maths: " + maths);
console.log("-----------------------------------------------------\n");
console.log("              Marking Information                 \n");
console.log("-----------------------------------------------------");
console.log(" Subject | Marks");
console.log("Science  | " + science);
console.log("English  | " + english);
console.log("Maths    | " + maths);

var textart = "★( ͡👁️ ͜ʖ ͡👁️)★( ͡👁️ ͜ʖ ͡👁️)★( ͡👁️ ͜ʖ ͡👁️)★( ͡👁️ ͜ʖ ͡👁️)";
console.log(textart);
